#!/bin/bash

source /etc/os-release

cat << EOF > db.json 
{
   "bomFormat" : "CycloneDX",
   "specVersion" : "1.5",
   "serialNumber" : "urn:uuid:c7dbc0d8-bcba-5946-aec2-0be72a6f5f3d",
   "version" : 1,
   "metadata" : {
      "timestamp" : "$(date -u '+%Y-%m-%dT%H:%M:%SZ')",
      "tools" : [
         {
            "name" : "transactional_update_generate_sbom",
            "version" : "0.1"
         }
      ]
   },
   "components": [

EOF

rpm -qa --queryformat '\t{\n\t\t"bom-ref": "pkg:%{NAME}-%{SIGMD5}",\n\t\t"type": "library",\n\t\t"name": "%{NAME}",\n\t\t"version": "%{VERSION}-%{RELEASE}",\n\t\t"purl": "pkg:rpm/%{VENDOR}/%{NAME}@%{VERSION}-%{RELEASE}&arch=%{ARCH}&upstream=%{SOURCERPM}&distro=@@ID@@-@@VERSION_ID@@",\n\t\t"licenses" : \[\n\t\t\t{\n\t\t\t"expression" : "%{LICENSE}"\n\t\t\t\n\t\t\t\}\n\t\t\],\n\t\t"publisher":"%{VENDOR}"\n\t\},\n' >> db.json
sed -i -e 's,rpm/openSUSE/,rpm/opensuse/,g' -e "s,@@ID@@,$ID,g" -e "s,@@VERSION_ID@@,$VERSION_ID,g" db.json
# temporary allow validation of SBOM
sed -i -e 's/SUSE-Public-Domain/CC0-1.0/g' db.json
cat << EOF  >> db.json
        {
         "type" : "operating-system",
         "name" : "$ID",
         "version" : "$VERSION_ID",
         "description" : "$NAME",
         "externalReferences" : [
            {
               "url" : "$BUG_REPORT_URL",
               "type" : "issue-tracker"
            },
            {
               "url" : "$HOME_URL",
               "type" : "website"
            }
         ]
      }
   ]
}
EOF

